version: 0.2
env:
    variables:
        S3_BUCKET: "vulnerable.pennington.io"
    parameter-store:
        SNYK_TOKEN: "SNYKAPIKey"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
            - npm install -g snyk
    pre_build:
        commands:
            - echo Testing vulnerabilities in NPM dependencies...
            - snyk test
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
    post_build:
         commands:
            - aws s3 rm s3://${S3_BUCKET} --recursive
            - aws s3 cp dist/vulnerable/ s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes